#!/usr/bin/env bash
# Bash script to transfer files
if [ $# -lt 3 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:"

if [ $? -ne 0 ]; then
    echo "Error: File transfer failed."
    exit 1
fi
