#!/usr/bin/env bash
# install and configure nginx
sudo apt update -y
sudo apt install nginx -y
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
sudo sed -i '/^server {$/a \ location /redirect_me {return 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ;}' /etc/nginx/sites-available/default
sudo bash -c "echo 'error_page 404 /404.html;\nlocation = /404.html {\nroot /var/www/html;\ninternal;\n}\n' >> /etc/nginx/sites-available/default"
sudo service nginx start
sudo nginx -s reload
