#!/usr/bin/env bash
# install and configure nginx
sudo apt update -y
sudo apt install nginx -y
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'
sudo bash -c "echo 'Ceci n'\"'\"'est pas une page' > /var/www/html/404.html"
sudo sed -i '/^server {$/a \ location /redirect_me {return 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ;}' /etc/nginx/sites-available/default
sudo bash -c "echo 'error_page 404 /404.html' >> /etc/nginx/sites-available/default"
sudo nginx -s reload
