#!/usr/bin/env bash
#sets up load balancers
sudo apt install -y haproxy
sudo echo -e "frontend haproxynode
\tbind *:80
\tmode http
\tdefault_backend nodes" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo echo -e "backend webservers
\tbalance roundrobin
\tserver 505456-web-01 52.3.254.46:80 check
\tserver 505456-web-02 100.26.211.242:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
